### ISSUE TITLE
The interfaces IDispatcher and IMessage are missing type hints

### ISSUE THREAD

**Issue by Revisor** [superfaktura/SmsManager#1]
Hello,
the interfaces (and classes implementing them) `IDispatcher` and `IMessage` are missing type hints in the method arguments.

```
IDispatcher::send($message)
```
should be
```
IDispatcher::send(IMessage $message)
```
And 
```
IMessage::addRecipient($recipient)
IMessage::removeRecipient($recipient)
```
should be
```
IMessage::addRecipient(IRecipient $recipient)
IMessage::removeRecipient(IRecipient $recipient)
```
You lose the power of interfaces by not type hinting them.

**Comment by adrianpanicek** [comment]
Thank you for suggestion. I've added mentioned typehints.
